import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"
import { KakaoScript } from "@/components/kakao-script"
import { SnackbarProvider } from "@/contexts/snackbar"

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <KakaoScript />
      <body
        className={`${pretendard.className} bg-background-assistive antialiased`}
      >
        <SnackbarProvider>{children}</SnackbarProvider>
      </body>
    </html>
  )
}
