import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"
import { TopBack } from "@/components/common"

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} bg-background-assistive antialiased`}
      > 
        <div className="m-auto w-full max-w-[420px]"><TopBack />{children}</div>
      </body>
    </html>
  )
}
